# Please edit this configuration file to match your environment (on Windows).
# Examples in comments below - check/change the paths.
#
#

logger:
  type: file
  level: error
  truncate_tools: true

mcp:
  targets:
    - name: filesystem
      # On windows update the target to use `node` and the absolute path to the server.
      # Use `npm i -g @modelcontextprotocol/server-filesystem` to install the server globally.
      # Use `npm -g root` to find the global node_modules path.`
      # target: "node c:/Program Files/nodejs/node_modules/@modelcontextprotocol/server-filesystem/dist/index.js ."
      target: "npx -y @modelcontextprotocol/server-filesystem ."
    - name: fetch
      target: "uvx mcp-server-fetch"
    - name: time
      target: "uvx mcp-server-time"
