default_model: haiku

tensorzero:
  base_url: http://localhost:3000
  api_key: verysecret

logger:
  level: "info"
  progress_display: true
  show_chat: true
  show_tools: true
  truncate_tools: true

mcp:
  targets:
    - name: tester
      target: "http://localhost:8000/t0-example-server/sse"
      transport: "sse"
      read_transport_sse_timeout_seconds: 300
